name: 'Greeting Action'
description: 'Greet someone when someone creates an issue or PR'
author: 'Karthik Nayak'
inputs:
  GITHUB_TOKEN:
    description: 'Github token for authentication'
    required: true

  issue_message:
    description: 'Put your customized issue message'
    required: false

  PR_message:
    description: 'Put your customized PR message'
    required: false

runs:
  using: 'node12'
  main: 'index.js'

branding:
  color: 'orange'
  icon: 'award'